# Generated by Django 3.1.3 on 2021-05-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Link_leonarod',
        ),
    ]
