# Generated by Django 3.1.3 on 2021-05-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20210517_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link_leonarod',
            new_name='Link_leonardo',
        ),
    ]
